### ISSUE TITLE
nginx reverse proxy on non-root location

### ISSUE THREAD

**Issue by adam-larson-lee** [balena-io/wifi-connect#352]
I'm working on a multi-container application that hosts a few different static files (grafana, couple custom SPAs, etc) via an nginx reverse-proxy and I'm trying to add a location for wifi-connect. Based on other services like grafana, node-red, etc, I should need to change configuration in wifi-connect for this to work but can't find anything relevant. I've tried a few different things here, including hosting wifi-connect from the root with no success.

What am I doing wrong here? Sample docker compose and nginx config below with just grafana and wifi-connect for simplicity.

```
version: '2.1'

volumes:
  data:

services:
 
  nginx:
    build : nginx
    ports:
        - '80:80'
        - '443:443'

  wifi-connect:
    build: wifi-connect
    expose:
      - '80'
    labels:
      io.balena.features.dbus: '1'
    cap_add:
      - NET_ADMIN
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - 'PORTAL_LISTENING_PORT=80'

  grafana:
    build: grafana
    expose:
      - '80'
    volumes:
      - 'data:/data'
    environment:
        - 'GF_PATHS_DATA=/data/grafana'
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_SESSION_PROVIDER=memory'
```
```
events {}

http {
  server {
    listen 80;
    root /usr/share/nginx/www;
    index index.html index.htm;

    location /data/ {
      proxy_pass http://grafana:80/;
    }

    location /wifi/ {      
      proxy_pass http://wifi-connect:80/;
    }
  }
}
